# Use the official Python base image
FROM python:3.9.14

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY app.py .

#EXPOSE 8501

# Specify the command to run on container start
#CMD ["streamlit", "run", "app.py"]
CMD ["streamlit", "run", "app.py", "--server.port", "8501"]

