# Use the official Python image from the Docker Hub
FROM python:3.9.14

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libhdf5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container

COPY main.py .
COPY ./scripts /app/scripts
COPY ./keys /app/keys
# Expose the port that the app runs on
EXPOSE 8000
#ENV GOOGLE_APPLICATION_CREDENTIALS=/app/keys/tensile-topic-424308-d9-17a256b9b21c.json

# Command to run the FastAPI app with uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
# 
