apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brain-tumor-classification
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  tempelate:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-container
          image: 
          imagePullPolicy: always
          ports:
            - containerPort:8080
          resources:
            requests:
              memory:
              cpu:
            limits:
              memory:
              cpu: 