apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brain-tumor-classification
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-container
          image: us-east1-docker.pkg.dev/tensile-topic-424308-d9/brain-tumor-classification-backend/backend:aadarshv7
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1"
              memory: "2"

