apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=   # base64 encoded value of 'postgres_user'
  password: YWRtaW4=  # base64 encoded value of 'secure_password'
