apiVersion: v1
kind: Service
metadata:
  namespace: brain-tumor-classification
  name: backend-service
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 8000         # Corrected field name to 'port'
      targetPort: 8000
