apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brain-tumor-classification
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-container
          image: us-east1-docker.pkg.dev/tensile-topic-424308-d9/brain-tumor-classification-frontend/frontend:v1 
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
      # imagePullSecrets:
      # - name: artifact-registry-secret