apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streamlit-frontend-hpa
  namespace: brain-tumor-classification
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:  
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 120 
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60  
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
