apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streamlit-frontend-hpa
  namespace: streamlit-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resources:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behaviour:
    scaleDown:
      stabalizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabalizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
