FROM python:3.9.14
LABEL maintainer="Aadarsh"

ARG AIRFLOW_VERSION=2.2.5
ARG AIRFLOW_HOME=/mnt/airflow

WORKDIR ${AIRFLOW_HOME}
ENV AIRFLOW_HOME=${AIRFLOW_HOME}

RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends \
    wget \
    curl \
    git \
    gcc \
    libhdf5-dev \
    libleveldb-dev \
    cmake\
    && apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt

# COPY ./.env /.env
# Upgrade pip separately to catch any issues
RUN pip install --upgrade pip && \
    useradd -ms /bin/bash -d ${AIRFLOW_HOME} airflow && \
    pip install apache-airflow==${AIRFLOW_VERSION} && \
    pip install -r /requirements.txt

#COPY ./entrypoint.sh ${AIRFLOW_HOME}/entrypoint.sh
# Copy the Airflow scripts
COPY ./ ${AIRFLOW_HOME}/

# Ensure the entrypoint script is executable
RUN chmod +x ${AIRFLOW_HOME}/entrypoint.sh

# Set ownership and permissions
RUN chown -R airflow:airflow ${AIRFLOW_HOME}

USER airflow

ENV GOOGLE_APPLICATION_CREDENTIALS=/mnt/airflow/keys/tensile-topic-424308-d9-17a256b9b21c.json
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

EXPOSE 8080
EXPOSE 8888

ENTRYPOINT [ "/mnt/airflow/entrypoint.sh" ]
