name: Build and Store Docker Image

on:
  push:
    branches:
      - shaun

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'

      - name: Build Docker image
        run: docker build . -t my-docker-image:latest

      - name: Save Docker image to file
        run: docker save my-docker-image:latest -o my-docker-image.tar

      - name: Upload Docker image to Google Cloud Storage
        run: gsutil cp my-docker-image.tar gs://brain-tumor-classification-registry/my-docker-image.tar
