name: backend

on:
  push:
    paths:
    - 'backend/**'
    branches:
    - Praneith10

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v2

      - name: authenticate to gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLECREDENTIALS }}

      - name: install google cloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tensile-topic-424308-d9
          #${{ secrets.GOOGLEPROJECT }}
          service_account_key: ${{ secrets.GOOGLECREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: tensile-topic-424308-d9
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
          docker build -t us-east1-docker.pkg.dev/tensile-topic-424308-d9/brain-tumor-classification-backend/backend:latest -f backend/dockerfile .
          docker push us-east1-docker.pkg.dev/tensile-topic-424308-d9/brain-tumor-classification-backend/backend:latest
