name: update_image_frontend

on:
  push:
    paths:
    - 'frontend/**'
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v2

      - name: authenticate to gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLECREDENTIALS }}

      - name: install google cloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id:  ${{ secrets.GOOGLEPROJECT }}
          service_account_key: ${{ secrets.GOOGLECREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT:  ${{ secrets.GOOGLEPROJECT }}
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev
          cd frontend
          docker build -t us-east1-docker.pkg.dev/tensile-topic-424308-d9/brain-tumor-classification-frontend/frontend:latest .
          docker push us-east1-docker.pkg.dev/tensile-topic-424308-d9/brain-tumor-classification-frontend/frontend:latest
